spring:
  application:
    name: gallerygather
  ## DB ??
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    username: gallery
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gallerygather:
  openapi:
    dev-url: http://localhost:8080


