spring:
  application:
    name: gallerygather
  ## DB ??
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    username: gallery
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
gallerygather:
  openapi:
    dev-url: http://localhost:8080

